version: "3"

services:
  database:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  server:
    build: ./packages/server
    depends_on:
      - database
    environment:
      DATABASE_URL: postgres://postgres:password@database/postgres
    links:
      - "database"
    ports:
      - "8081:8080"
    volumes:
      - .:/usr/src/app:ro
  client:
    build: ./packages/client
    depends_on:
      - database
    ports:
      - "8082:8080"
    volumes:
      - .:/usr/src/app:ro
  gateway:
    depends_on:
      - server
      - client
    image: nginx
    ports:
      - "8080:8080"
    links:
      - "server"
      - "client"
    volumes:
      - ./dev/nginx:/etc/nginx/templates:ro

volumes:
  postgres_data:
